#Notice:
#Path is set the seteings file located at
#C:\Users\Thor9\AppData\Roaming\Ultralytics\settings.yaml

path: utils\YOLO\data 
train: images\train
val: images\val
test: images\test


#classes
names:
  0: stone